server:
  port: 8888

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:15432/manager"
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
      
app:
  jwtSecret: secret
  jwtExpirationMs: 86400000
